#---------- Initialize cluster
- name: reset kubernetes component
  shell: kubeadm reset --force
  register: reset_cluster

- name: Create cluster with kubeadm
  shell: sudo kubeadm init --kubernetes-version=1.28.0 --pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans {{ hostvars[groups['master'][0]].ansible_host }}
  register: init_cluster

- name: create .kube directory
  file:
    path: "$HOME/.kube/"
    state: directory
    mode: 0755

- name: Copy admin.conf to Home directory
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "$HOME/.kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

#---------- Download and apply the calico network add-on
- name: Download calico manifest to the cluster.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
    dest: ~/calico.yaml
    mode: '0664'

- name: Apply calico manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: ~/calico.yaml

#---------- Create the workers join token
- name: create join token
  shell: sudo kubeadm token create --print-join-command
  register: join_token

- name: save join token
  shell: "echo {{ join_token.stdout }} > join.sh"

- name: save to local 
  run_once: true
  fetch: src=join.sh dest="{{ playbook_dir }}/buffer/" flat=yes

- name: create .kube repo
  file:
    path: .kube
    state: directory

- name: Copy admin.conf to Home directory
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: .kube/config
    remote_src: true