apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notication-email-secret
  namespace: default
spec:
  encryptedData:
    EMAIL_PASS: AgAl+kjDnBkzFRkEf+7Km2ldp59pKsXDPnkSTkujjXq7Pn379JyNT211Q7kAJ+tcOqf9IoBExxKcleAX5xIOQI1zR9YzBdTfIHPsDtFdyJKj96D0SfSe3FL+6OHjK3eoAjlNZix+myaC7+Ne6B7IOtiTTMxdMKWy8nz3eEvkkk7uxxdtQ5Ne0E1CpyXNoiGBrCxeUHzPgns2cBqrkBs3IhhvDIH4F5WyWKI87p+cjx2tx6d16WrGSNHNDD7Po2lRYeeEHeU2Erehd5uQ+hMaIisHWWrzHcaQ7pL+Z4KgiQz9VpgxjNSuQwkbto61KSsWnm8EY7teo68xbjyTQ3qgrDUGwjK5PEsjDeCFlc75940eYMWVP6RJq3ibsl8nyaDBfnt2Nkw4BlNvSubaVMAyM7IKoox+M3G6mxSKAmYcbtHt1i1ix2r5+9NspJn3BLeKGxKqBXo23vWPG2xcJToTZuiV48pS30BV6jJdqA4C4FZ1OmKapz2vW/Xc9Pgn/TKD1aaAsMcp3mMAS//XwDrPr+6bi3m3vVakZ/rSFAIh+IKgXuq3sYqk2IHJueoqJ8U72n2RHMn7f3orYSsCachS6Vzh9YAphyV5+O0NswpVMvmJXkxRPZA7q6DJf7Sya6Qt3Ef9bBh+EG0IfB+nSSg3zvnlcFmK96llZzzP0JKI7XZj4BBetKZZgvC9YdGh76LGgYJBx8pIuRja51EaDdTv9fRFtI6R
    EMAIL_USER: AgB7T5J3dO1cFSHBzS4RCpR8s4ZdaEjGGZvV/2qtu9+Es4OjQVyAbB1ChanAH6/+vTvls5pc5d5pkoZeooLEhTf5VDKKd2eNa56b06xWBRMisn8jQ69ecycVKOouEtRQ4+1CkjDgD7oiTm83kZBrZRSq2CVsFMTYaq6SXhydKF8sLQvDwoyKmkX3rNbMr77eOljBI4HsJ+H5zQngUiApK9W8kiIN05DVWvTjMUFL9F+4GzjWTXF2Cje7qkwFJ4Vt1ap6tndNX5MiqqeJkWuqBjhuig5uQoXa8M4mb9dtGHIaLxSmkNjOXfo5n2NmD4J9dzxXeILXQbvNcLU+1SNlshHpXyKD+VCAW9bMGNBZle84muFRs3R3d4pqKnYtwK9hBk/z+hdLuFrZmFEorSA5L0HvWIpMdnrezrOjFg4G3hVBtpjP9YF2DCqG8CTybQJrJEYmNxKopsDeYGVw/18h/E72kEIKpk+oFhAJVQcaH35txa8Ka29tngpBQr1yM7MfxWmSn7nhqqEse4rkLArMSEDeXXyx45WwzIaKRrMyTopNGKzhU2j2zfJyxZ0fexh310ziO92OMqOg5FAABYjvnfo999VY9ATaWZT0qZHeUlFIxQky20zgNMOcq9iTHc3jtskQiMtHvuSJwTGlMDATKkLHype6mmlKdjtYJd++iMrGhPxNwk/41RxGnQ/ORZbkP04XVr3lnqt0MxDKjocjQ87qzIhbmYwZnLwykYw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification
        project: microservices_mp4-to-mp3-converter
      name: notication-email-secret
      namespace: default
    type: Opaque

