---
- name: Install kubectl command line utility
  community.general.snap:
    name: kubectl
    state: present
    classic: yes
    channel: 1.30/stable

- name: Enable microk8s addons
  shell: |
    microk8s enable ingress
    microk8s enable dns
    microk8s enable hostpath-storage

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/ubuntu/.kube"
    state: directory
    mode: "0755"
    owner: ubuntu
    group: ubuntu

- name: Save kubeconfig to .kube/config
  shell: microk8s config > /home/ubuntu/.kube/config
  args:
    creates: "/home/ubuntu/.kube/config"