- name: Add Helm GPG key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
    keyring: /usr/share/keyrings/helm.gpg

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add Helm repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    update_cache: yes

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present

- name: Install sealed secrets
  kubernetes.core.helm:
    release_name: sealed-secrets
    chart_ref: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
    namespace: kube-system
    kubeconfig: /home/ubuntu/.kube/config
    
- name: Copy kubeseal certs
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../keys/kubeseal/"
    dest: /home/ubuntu/.kube/kubeseal-certs/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Create kubeseal cert TLS secrets
  become: false
  shell: |
    kubectl -n kube-system create secret tls kubeseal-seal-secret --cert /home/ubuntu/.kube/kubeseal-certs/tls.crt --key /home/ubuntu/.kube/kubeseal-certs/tls.key

- name: Label kubeseal cert TLS secrets
  become: false
  shell: |
    kubectl -n kube-system label secret kubeseal-seal-secret sealedsecrets.bitnami.com/sealed-secrets-key=active
  
- name: Refresh kubeseal controller pod
  become: false
  shell: |
    kubectl -n kube-system delete pod -l app.kubernetes.io/name=sealed-secrets