# - name: Add Helm GPG key
#   ansible.builtin.command:
#     cmd: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
#     args:
#       warn: false
- name: Add Helm GPG key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
    keyring: /usr/share/keyrings/helm.gpg

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

# - name: Add Helm apt repository
#   ansible.builtin.apt_repository:
#     repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
#     filename: helm-stable-debian
#     state: present

- name: Add Helm repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    update_cache: yes

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present

- name: Install sealed secrets
  kubernetes.core.helm:
    release_name: sealed-secrets
    chart_ref: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
    namespace: kube-system
    kubeconfig: /home/ubuntu/.kube/config
    