---

#---------- Setup prerequisites
- hosts: all
  name: setup kube prerequisites
  roles:
    - { role: kube-prerequisites, tags: kube-prerequisites }
  become: true

#---------- Install containerd docker engine and Docker Compose
- hosts: all
  name: Install containerd
  roles:
    - { role: containerd, tags: containerd }
  become: true

#---------- Install kubeadm kuebctl kubelet
- hosts: all
  name : Install kubeadm kuebctl kubelet
  roles:
    - { role: kubelet-kubeadm-kubectl, tags: kubelet-kubeadm-kubectl}
  become: true
  
#---------- Configure the cluster
- hosts: master
  name: cluster init and installing calico networking solution
  become: true
  roles:
    - { role: init-cluster, tags: init-cluster }

#---------- Join the worker nodes to the cluster
- hosts: workers
  name: copy token to workers
  become: true
  tasks:
    - name: save join token to workers
      copy: 
          src: "{{ playbook_dir }}/buffer/join.sh"
          dest: "./"
    - name: execute join token
      command: sh join.sh

- hosts: master
  name: save kubeconfig to local
  become: true
  tasks:
    - name: save kubeconfig to local
      run_once: true
      fetch: src=$HOME/.kube/config dest="{{ playbook_dir }}/../kube/" flat=yes
          