---
- hosts: all
  name: Install microk8s
  become: true
  tasks:
  - name: Install microk8s using snap
    community.general.snap:
      name: microk8s
      state: present
      classic: yes

- hosts: master
  name: Initialize cluster
  become: true
  roles:
  - { role: microk8s, tags: microk8s }

- hosts: workers
  name: Join workers to the cluster
  become: true
  serial: 1
  roles:
  - { role: join-workers, tags: join-workers }

- hosts: master
  name: Deploy microservices
  roles:
  - { role: deploy-microservices, tags: deploy-microservices }
