services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local