- name: Clone git repository
  ansible.builtin.git:
    repo: https://github.com/aditya-shrivastavv/microservices-project-mp3-converter.git
    dest: /home/ubuntu/microservices-project-mp3-converter

- name: Deploy application on kubernetes
  shell: kubectl apply -f $PROJECT_PATH/src/{{ item }}
  loop:
    - gateway/k8s/
    - rabbit/k8s/
    - auth/k8s/
    - mysql/k8s/
    - mongodb/k8s/
    - notification/k8s/
    - converter/k8s/
  environment:
    PROJECT_PATH: /home/ubuntu/microservices-project-mp3-converter